"""empty message

Revision ID: 39314c4cb5ca
Revises: 766ef91d2ae1
Create Date: 2022-03-06 14:47:29.811586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39314c4cb5ca'
down_revision = '766ef91d2ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forex__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('label', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forex__data')
    # ### end Alembic commands ###
